# Numpy

In [1]:
import numpy as np

## 1. Creation

- To create 1 dimentional ndarray -> array we first need a list/tuple of elements
- we use this function `np.array()` to convert that list into array

In [2]:
l1 = [10, 12, 45, 32, 12, 34, 56, 78, 21, 34, 23, 77, 54, 23, 40, 22, 16, 29]

In [3]:
res = []
for ele in l1:
    res.append(ele * 3)
print(res)

print([x*3 for x in l1])

[30, 36, 135, 96, 36, 102, 168, 234, 63, 102, 69, 231, 162, 69, 120, 66, 48, 87]
[30, 36, 135, 96, 36, 102, 168, 234, 63, 102, 69, 231, 162, 69, 120, 66, 48, 87]


In [4]:
arr1 = np.array(l1)

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1 * 3

array([ 30,  36, 135,  96,  36, 102, 168, 234,  63, 102,  69, 231, 162,
        69, 120,  66,  48,  87])

## 2. Accessing elements

- This is similar to lists/tuples
- we'll use `[]` to extract elements by indexes
- indexing is from 0 to n-1

In [7]:
arr1[4]

12

In [8]:
arr1[5:10]

array([34, 56, 78, 21, 34])

In [9]:
arr1[-1]

29

In [10]:
# Task : From list l1, get random elements 0,1,6,10,11
req_pos = [0,1,6,10,11]
res = []
for p in req_pos:
    res.append(l1[p])
res

[10, 12, 56, 23, 77]

In [11]:
# Task : From array arr1, get random elements 0,1,6,10,11
# a list containing the required positions : [0,1,6,10,11]
# just pass this list to the [] extractor

arr1[[0,1,6,10,11]]



array([10, 12, 56, 23, 77])

## 3. Applying conditions

- we can use the regular loop on arrays to apply conditions
- Owing to the vectorized nature of numpy, we can use the [] extractor to apply conditions
    - the concept of **boolean indexing** is being used in this extraction
- ***The conditions ~~MUST~~ be put inside the ()***
> e.g. `arr1[(arr1 < 40)]`

In [12]:
# task : 
# from arr1, get all elements that are < 40

res = []
for ele in arr1:
    if ele < 40:
        res.append(ele)
res = np.array(res)
res

array([10, 12, 32, 12, 34, 21, 34, 23, 23, 22, 16, 29])

In [13]:
# from arr1, get all elements that are < 40

arr1[(arr1 < 40)]

array([10, 12, 32, 12, 34, 21, 34, 23, 23, 22, 16, 29])

In [14]:
arr1 < 40

# this thing is boolean index
# either the index is there (True) or it is not there (False)
# elements corresponding to True will be extracted into a new array

array([ True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True, False,  True,  True,  True])

In [15]:
# Task : from arr1 get elements that are > 30 and < 70

# arr1[arr1 > 30 and arr1 < 70] # wrong
# arr1[(arr1 > 30) and (arr1 < 70)] # wrong
arr1[(arr1 > 30) & (arr1 < 70)] # correcto!

array([45, 32, 34, 56, 34, 54, 40])

## 4. Attributes

In [16]:
print(dir(arr1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [17]:
arr1.sum()

618

In [18]:
arr1.mean()

34.333333333333336

## 5. Homogenous nature of ndarray

In [19]:
l2 = [1,3,4,2,5,6,7]

In [20]:
arr2 = np.array(l2)
arr2

array([1, 3, 4, 2, 5, 6, 7])

In [21]:
arr2.dtype

dtype('int32')

In [22]:
l3 = [4,3,6,9.4,23.4,56.7]
l3

[4, 3, 6, 9.4, 23.4, 56.7]

In [23]:
arr3 = np.array(l3)
arr3

array([ 4. ,  3. ,  6. ,  9.4, 23.4, 56.7])

In [24]:
arr3.dtype

dtype('float64')

In [25]:
L4 = [2,4,2,34.5,6.4,8.7,'a','b','c']

In [26]:
arr4 = np.array(L4)
arr4

array(['2', '4', '2', '34.5', '6.4', '8.7', 'a', 'b', 'c'], dtype='<U32')

In [27]:
L5 =[1,2,3,(6,7)]
L5

[1, 2, 3, (6, 7)]

In [28]:
L5[3][0]

6

In [29]:
np.array(L5)

array([1, 2, 3, (6, 7)], dtype=object)

In [30]:
L1 =[1,2,3,(6,7)]
type(L1)
np.array(L1)

array([1, 2, 3, (6, 7)], dtype=object)

In [31]:
l1

[10, 12, 45, 32, 12, 34, 56, 78, 21, 34, 23, 77, 54, 23, 40, 22, 16, 29]

In [32]:
print(set(l1))

{32, 34, 40, 10, 12, 45, 78, 77, 16, 21, 54, 23, 56, 22, 29}


In [33]:
set(l1)

{10, 12, 16, 21, 22, 23, 29, 32, 34, 40, 45, 54, 56, 77, 78}

# Pandas

- Pandas provides a 2d heterogenous table - **DataFrame**
- A combination of multiple one dimentional homogenous data structures
    - pandas provides a one dimentional homogenous data structure **Series**

In [34]:
import pandas as pd

## Pandas Series

### 1. Creating Pandas Series

- list/tuple/dict/set that contain our data
- convert that into pandas Series using `pd.Series()`

In [35]:
ser1 = pd.Series(l1)
type(ser1)

pandas.core.series.Series

In [36]:
ser1

# displays the location or loc or index along with the values

0     10
1     12
2     45
3     32
4     12
5     34
6     56
7     78
8     21
9     34
10    23
11    77
12    54
13    23
14    40
15    22
16    16
17    29
dtype: int64

### 2. The loc, locations or indexes 

- there are two types of indexes in pd.Series
- the regular integer locations or indexes - 0 to len-1
> `iloc`
- along with that it can also have external, user defined, key-style indexes
> `loc`
- when the user is not setting anything, then loc == iloc

In [37]:
ser2 = pd.Series(l1, index = list('abcdefghijklmnopqr'))

In [38]:
ser2

a    10
b    12
c    45
d    32
e    12
f    34
g    56
h    78
i    21
j    34
k    23
l    77
m    54
n    23
o    40
p    22
q    16
r    29
dtype: int64

In [39]:
ser3 = pd.Series(l3, index = ["ruchi","abhishek","anil","shravanti","sachin","anshul"])
ser3

# loc : ["ruchi","abhishek","anil","shravanti","sachin","anshul"]
# iloc : 0,1,2,3,4,5

ruchi         4.0
abhishek      3.0
anil          6.0
shravanti     9.4
sachin       23.4
anshul       56.7
dtype: float64

### 2. Access elements

- for series we can directly use `[]` but it's not advisable

- instead `.loc[]` and `.iloc[]`

In [40]:
ser2.iloc[3]

32

In [41]:
ser2.loc['d']

32

In [42]:
# get first 5 elements

ser2.iloc[0:5]

a    10
b    12
c    45
d    32
e    12
dtype: int64

In [43]:
# get elements a,g,h,n,m,p
ser2.loc[["a",'g','h','n','m','p']]

a    10
g    56
h    78
n    23
m    54
p    22
dtype: int64

In [44]:
ser3

ruchi         4.0
abhishek      3.0
anil          6.0
shravanti     9.4
sachin       23.4
anshul       56.7
dtype: float64

In [45]:
ser1
# loc == iloc

0     10
1     12
2     45
3     32
4     12
5     34
6     56
7     78
8     21
9     34
10    23
11    77
12    54
13    23
14    40
15    22
16    16
17    29
dtype: int64

In [46]:
ser1[3]

32

In [47]:
ser1.iloc[3]

32

In [48]:
ser1.loc[3]

32

In [49]:
ser1.iloc[0:10]

0    10
1    12
2    45
3    32
4    12
5    34
6    56
7    78
8    21
9    34
dtype: int64

In [50]:
ser1.loc[0:10]
# the upper bound is INCLUDED

0     10
1     12
2     45
3     32
4     12
5     34
6     56
7     78
8     21
9     34
10    23
dtype: int64

### 3. Applying conditions
- conditions are applied as **bollean indexes**
- boolean indexing can be implemented only on `loc[]`

In [51]:
# task : 
# from ser1, get all elements that are < 40

res = []
for ele in ser1:
    if ele < 40:
        res.append(ele)
res = pd.Series(res)
res

0     10
1     12
2     32
3     12
4     34
5     21
6     34
7     23
8     23
9     22
10    16
11    29
dtype: int64

In [52]:
# from ser1, get all elements that are < 40

ser1.loc[(ser1 < 40)]

0     10
1     12
3     32
4     12
5     34
8     21
9     34
10    23
13    23
15    22
16    16
17    29
dtype: int64

In [53]:
ser1 < 40

# this thing is boolean index
# either the index is there (True) or it is not there (False)
# elements corresponding to True will be extracted into a new array

0      True
1      True
2     False
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11    False
12    False
13     True
14    False
15     True
16     True
17     True
dtype: bool

In [54]:
# Task : from ser1 get elements that are > 30 and < 70

# ser1.loc[ser1 > 30 and ser1 < 70] # wrong
# ser1.loc[(ser1 > 30) and (ser1 < 70)] # wrong
ser1.loc[(ser1 > 30) & (ser1 < 70)] # correcto!

2     45
3     32
5     34
6     56
9     34
12    54
14    40
dtype: int64

### 4. Attributes

In [55]:
print(dir(l1))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [56]:
print(dir(arr1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [57]:
print(dir(ser1))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdiv

## Broadcasting in numpy and pandas

In [58]:
l3 = [20,40,60,10]
l4 = [90,30,10,30]

l3 + l4


# [110,70,70,40]

[20, 40, 60, 10, 90, 30, 10, 30]

In [59]:
s1 = pd.Series(l3)
s2 = pd.Series(l4)

In [60]:
s1 + s2

0    110
1     70
2     70
3     40
dtype: int64

In [61]:
s1 * s2

0    1800
1    1200
2     600
3     300
dtype: int64

In [63]:
s1/10

0    2.0
1    4.0
2    6.0
3    1.0
dtype: float64

In [64]:
a1 = np.array(l3)
a2 = np.array(l4)

In [65]:
a1 + a2

array([110,  70,  70,  40])

## `numpy.arange`

In [68]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [69]:
list(range(0,10,0.5))

# 0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5 ... 9, 9.5

TypeError: 'float' object cannot be interpreted as an integer

In [71]:
list(np.arange(0,10,0.5))


[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5]

In [72]:
list(range(0.5,10.5,1))

TypeError: 'float' object cannot be interpreted as an integer

# Dataframes

- tables - 2 dimentional, hetrerogenous DS
- rows (indexed) and columns (named)
- columns are homogenous - Series
- collection of Series

Topics : 
	1. Create and Importing Dataframes
	2. Data munging and operations
		- data manipulations
			- structure
			- content
		- operations
	3. Visualizations
	4. Business Knowledge/Heuristics
	5. Introductory Statistics


## Creating and Importing

### 1. from pandas Series

- Series --> all the Series should be of the same size
- these same sized series can be combined to form a dataframe
- We'll use `pd.concat()` to combine them into a dataframe
    - it takes list as an input
    - that list can contain series, df etc
    - the default concatenation is row wise - one below the other
        `axis = 0`
    - this can be changed by using an arg - `axis=1` - which enables column wise concatenation

In [78]:
x1 = pd.Series([1,2,3,4,5,6],name = "Emp_ID")
x2 = pd.Series([2367,2472,8646,3583,5835,2472],name = "Emp_Sal")
x3 = pd.Series(["Anil","Sravanti","Sakshi","Vivek","M","Sachin"], name="Emp_Names")
x4 = pd.Series(["12Oct2015","18Nov2016","10Nov2018","05Dec2015","14Feb2020","04Nov2018"],name="DoJ")

In [81]:
x3

0        Anil
1    Sravanti
2      Sakshi
3       Vivek
4           M
5      Sachin
Name: Emp_Names, dtype: object

In [82]:
# Now, concat all these series
pd.concat([x1,x2,x3,x4])

0            1
1            2
2            3
3            4
4            5
5            6
0         2367
1         2472
2         8646
3         3583
4         5835
5         2472
0         Anil
1     Sravanti
2       Sakshi
3        Vivek
4            M
5       Sachin
0    12Oct2015
1    18Nov2016
2    10Nov2018
3    05Dec2015
4    14Feb2020
5    04Nov2018
dtype: object

In [85]:
emp_data = pd.concat([x1,x2,x3,x4],axis=1)
emp_data

Emp_ID  Emp_Sal Emp_Names        DoJ
0       1     2367      Anil  12Oct2015
1       2     2472  Sravanti  18Nov2016
2       3     8646    Sakshi  10Nov2018
3       4     3583     Vivek  05Dec2015
4       5     5835         M  14Feb2020
5       6     2472    Sachin  04Nov2018

In [86]:
type(emp_data)

pandas.core.frame.DataFrame

## 2. From a dictionary

In [88]:
emp_dict = {
    "Emp_ID" : [1,2,3,4,5,6],
    "Emp_Sal" : [2367,2472,8646,3583,5835,2472],
    "Emp_Names" : ["Anil","Sravanti","Sakshi","Vivek","M","Sachin"],
    "DoJ" : ["12Oct2015","18Nov2016","10Nov2018","05Dec2015","14Feb2020","04Nov2018"]
}

In [89]:
pd.DataFrame(emp_dict)

Emp_ID  Emp_Sal Emp_Names        DoJ
0       1     2367      Anil  12Oct2015
1       2     2472  Sravanti  18Nov2016
2       3     8646    Sakshi  10Nov2018
3       4     3583     Vivek  05Dec2015
4       5     5835         M  14Feb2020
5       6     2472    Sachin  04Nov2018

## 3. Importing CSV Files

- any text delimited file : delimiter decides the columns
- file path + file name + extention
- the delimeter or separator : sep

In [90]:
# Folders and directories
%pwd

'E:\\DSP January 2020 BLR'

In [91]:
import os

In [92]:
os.getcwd()

'E:\\DSP January 2020 BLR'

In [96]:
'E:\DSP January 2020 BLR'

'E:\\DSP January 2020 BLR'

In [99]:
path = 'F:\ALABS Services Master\HR Analytix Master\Insights Old' # incorrect

# correct
path = 'F:\\ALABS Services Master\\HR Analytix Master\\Insights Old'
path = 'F:/ALABS Services Master/HR Analytix Master/Insights Old'

# best alternative --- raw strings
path = r'F:\ALABS Services Master\HR Analytix Master\Insights Old'


In [106]:
# Importing CSV is done using pd.read_csv()
# - file path
# - sep = ","

stores = pd.read_csv("DataSets/stores.csv")


In [110]:
path = r"C:\Users\sunitprasad\Documents"

cust = pd.read_csv(path +  r'\cust_data.csv',sep = ",")

In [112]:
# How to read non comma sep files???
pd.read_csv("DataSets/sample_data.txt", sep = "\t")

Type  gender   id  session  schtyp  level
0     general       0   70        4       1      1
1  vocational       1  121        4       2      1
2     general       0   86        4       3      1
3  vocational       0  141        4       3      1
4    academic       0  172        4       2      1
5    academic       0  113        4       2      1
6     general       0   50        3       2      1
7    academic       0   11        1       2      1

## 4. Importing Excel files

- File path, name extn
- sheet_name
    - by default -> first sheet or sheet_name = 0
    - or else mention sheet name -> 
        - `sheet_name = 3` # 4th sheet will be read
        - Specify the exact name instead of index `sheet_name = "March_data"`
        

In [113]:
sheet_1 = pd.read_excel("DataSets/AutoInsurance.xlsx")

In [114]:
sheet_1.head()

CASENUM  ATTORNEY  CLMSEX  MARITAL  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        5         1     1.0      NaN       2.0       1.0    50.0  34.940
1       13         2     2.0      2.0       1.0       1.0    28.0  10.892
2       66         2     1.0      2.0       2.0       1.0     5.0   0.330
3       71         1     1.0      1.0       2.0       2.0    32.0  11.037
4       96         2     1.0      4.0       2.0       1.0    30.0   0.138

In [115]:
# we now need second sheet, mention the sheet index
sheet_2 = pd.read_excel("DataSets/AutoInsurance.xlsx",sheet_name=1)

# or, pass the name if you know
sheet_2 = pd.read_excel("DataSets/AutoInsurance.xlsx",sheet_name="AutoClaims")

In [119]:
# How ton read all the sheets together
#  - use a loop on sheet names
#  - read the xls sheets into a dictionary

# Step 1
# Open the file

insurance_excel = pd.ExcelFile("DataSets/AutoInsurance.xlsx")
# this now has a connection to the file and also, it has the metadata about the file

# Step 2
# Get the sheet names

insurance_excel.sheet_names

# Step 3
# How do we read one sheet out of all the sheets
# parse() will process and import the data

insurance_excel.parse(sheet_name="AutoClaims")

CLAIMCASES     STATE CLASS     PAID
0          27296  STATE 14   C6   1134.44
1           8716  STATE 15   C6   3761.24
2          16795  STATE 15   C11  7842.31
3          16721  STATE 15   F6   2384.67
4           1092  STATE 15   F6    650.00
...          ...       ...   ...      ...
6768        3562  STATE 15   C71    39.31
6769       32142  STATE 02   C71    35.00
6770       24933  STATE 17   C7B    27.46
6771        7769  STATE 01   C71    25.00
6772        7142  STATE 15   C7B    21.58

[6773 rows x 4 columns]

In [121]:
# Step 4
# how to read all the sheets
all_sheet_data = {}
for sheet in insurance_excel.sheet_names:
    all_sheet_data[sheet] = insurance_excel.parse(sheet_name=sheet)

In [122]:
all_sheet_data

{'AutoBi':       CASENUM  ATTORNEY  CLMSEX  MARITAL  CLMINSUR  SEATBELT  CLMAGE    LOSS
 0           5         1     1.0      NaN       2.0       1.0    50.0  34.940
 1          13         2     2.0      2.0       1.0       1.0    28.0  10.892
 2          66         2     1.0      2.0       2.0       1.0     5.0   0.330
 3          71         1     1.0      1.0       2.0       2.0    32.0  11.037
 4          96         2     1.0      4.0       2.0       1.0    30.0   0.138
 ...       ...       ...     ...      ...       ...       ...     ...     ...
 1335    34210         2     1.0      2.0       2.0       1.0     NaN   0.576
 1336    34220         1     2.0      1.0       2.0       1.0    46.0   3.705
 1337    34223         2     2.0      1.0       2.0       1.0    39.0   0.099
 1338    34245         1     2.0      2.0       1.0       1.0    18.0   3.277
 1339    34253         2     2.0      2.0       2.0       1.0    30.0   0.688
 
 [1340 rows x 8 columns],
 'AutoClaims':       CLAIM

In [127]:
# Step 5 : How to retrieve the data???
all_sheet_data.keys()
all_sheet_data['AutoBi']

CASENUM  ATTORNEY  CLMSEX  MARITAL  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         1     1.0      NaN       2.0       1.0    50.0  34.940
1          13         2     2.0      2.0       1.0       1.0    28.0  10.892
2          66         2     1.0      2.0       2.0       1.0     5.0   0.330
3          71         1     1.0      1.0       2.0       2.0    32.0  11.037
4          96         2     1.0      4.0       2.0       1.0    30.0   0.138
...       ...       ...     ...      ...       ...       ...     ...     ...
1335    34210         2     1.0      2.0       2.0       1.0     NaN   0.576
1336    34220         1     2.0      1.0       2.0       1.0    46.0   3.705
1337    34223         2     2.0      1.0       2.0       1.0    39.0   0.099
1338    34245         1     2.0      2.0       1.0       1.0    18.0   3.277
1339    34253         2     2.0      2.0       2.0       1.0    30.0   0.688

[1340 rows x 8 columns]

In [128]:
all_sheet_data['AutoClaims']

CLAIMCASES     STATE CLASS     PAID
0          27296  STATE 14   C6   1134.44
1           8716  STATE 15   C6   3761.24
2          16795  STATE 15   C11  7842.31
3          16721  STATE 15   F6   2384.67
4           1092  STATE 15   F6    650.00
...          ...       ...   ...      ...
6768        3562  STATE 15   C71    39.31
6769       32142  STATE 02   C71    35.00
6770       24933  STATE 17   C7B    27.46
6771        7769  STATE 01   C71    25.00
6772        7142  STATE 15   C7B    21.58

[6773 rows x 4 columns]

In [136]:
def ExcelReader(path=""):
    file = pd.ExcelFile(path)
    data_frames = {}
    for sheet in file.sheet_names:
        data_frames[sheet] = file.parse(sheet_name = sheet)
    return data_frames

In [138]:
ExcelReader(path="DataSets/AutoInsurance.xlsx")

{'AutoBi':       CASENUM  ATTORNEY  CLMSEX  MARITAL  CLMINSUR  SEATBELT  CLMAGE    LOSS
 0           5         1     1.0      NaN       2.0       1.0    50.0  34.940
 1          13         2     2.0      2.0       1.0       1.0    28.0  10.892
 2          66         2     1.0      2.0       2.0       1.0     5.0   0.330
 3          71         1     1.0      1.0       2.0       2.0    32.0  11.037
 4          96         2     1.0      4.0       2.0       1.0    30.0   0.138
 ...       ...       ...     ...      ...       ...       ...     ...     ...
 1335    34210         2     1.0      2.0       2.0       1.0     NaN   0.576
 1336    34220         1     2.0      1.0       2.0       1.0    46.0   3.705
 1337    34223         2     2.0      1.0       2.0       1.0    39.0   0.099
 1338    34245         1     2.0      2.0       1.0       1.0    18.0   3.277
 1339    34253         2     2.0      2.0       2.0       1.0    30.0   0.688
 
 [1340 rows x 8 columns],
 'AutoClaims':       CLAIM

## SAS Files

- sas7bdat

In [142]:
sas_data = pd.read_sas("DataSets/CredidCardUsage.sas7bdat",encoding="Latin-1")

In [143]:
phrase=input("enter a phrase:")
l=phrase.split()
print(l)
upper_case=0
lower_case=0
for i in range(0,len(l)):
    for alpha in i[]:
        if alpha[i].isupper():
            upper_case+=1
        else:
            lower_case+=1
print("lower_case:" ,lower_case)
print("upper_case:" ,upper_case)


SyntaxError: invalid syntax (<ipython-input-143-602ea58b9dcf>, line 7)

In [152]:
ip = "Python PanDAs Class 5 of 30"

lower = 0
upper = 0
digit = 0
for ele in list(ip):
    if ele.isupper():
        upper += 1
    elif ele.islower():
        lower += 1
    elif ele.isdigit():
        digit += 1
print("No of upper case is:", upper, "and number of lower case is:",lower,"and no of digits are:",digit)

No of upper case is: 5 and number of lower case is: 14 and no of digits are: 3


In [153]:
l1 = [33,45,32,67,86] # replace 32 with 40

In [156]:
l1[l1.index(32)] = 40

In [157]:
l1

[33, 45, 40, 67, 86]

# Data Manipulations

In [164]:
stores = pd.read_csv("DataSets/stores.csv")

stores

StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0   
1     STR102      Apparel Zone       Apparel    Delhi           21.0   
2     STR103       Super Bazar  Super Market    Delhi           22.8   
3     STR104      Super Market  Super Market    Delhi           21.4   
4     STR105     Central Store  Super Market    Delhi           18.7   
5     STR106      Apparel Zone       Apparel    Delhi           18.1   
6     STR107     Fashion Bazar       Apparel    Delhi           14.3   
7     STR108     Digital Bazar  Electronincs    Delhi           24.4   
8     STR109  Electronics Zone  Electronincs  Chennai           22.8   
9     STR110      Apparel Zone       Apparel  Chennai           19.2   
10    STR111       Super Bazar  Super Market  Chennai           17.8   
11    STR112      Super Market  Super Market  Chennai           16.4   
12    STR113     Central Store  Super Market  Chennai           17.3   
13    STR114      Apparel Zone       Apparel  Chennai           15.2   
14    STR115     Fashion Bazar       Apparel  Chennai           10.4   
15    STR116     Digital Bazar  Electronincs  Chennai           10.4   
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7   
17    STR118      Apparel Zone       Apparel   Mumbai           32.4   
18    STR119       Super Bazar  Super Market   Mumbai           30.4   
19    STR120      Super Market  Super Market   Mumbai           33.9   
20    STR121     Central Store  Super Market   Mumbai           21.5   
21    STR122      Apparel Zone       Apparel   Mumbai           15.5   
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2   
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3   
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2   
25    STR126      Apparel Zone       Apparel  Kolkata           27.3   
26    STR127       Super Bazar  Super Market  Kolkata           26.0   
27    STR128      Super Market  Super Market  Kolkata           30.4   
28    STR129     Central Store  Super Market  Kolkata           15.8   
29    STR130      Apparel Zone       Apparel  Kolkata           19.7   
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0   
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4   

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620   
1          60       160.0              110            3.90       2.875   
2          40       108.0               93            3.85       2.320   
3          60       258.0              110            3.08       3.215   
4          80       360.0              175            3.15       3.440   
5          60       225.0              105            2.76       3.460   
6          80       360.0              245            3.21       3.570   
7          40       146.7               62            3.69       3.190   
8          40       140.8               95            3.92       3.150   
9          60       167.6              123            3.92       3.440   
10         60       167.6              123            3.92       3.440   
11         80       275.8              180             NaN       4.070   
12         80       275.8              180             NaN       3.730   
13         80       275.8              180             NaN       3.780   
14         80       472.0              205            2.93       5.250   
15         80       460.0              215            3.00       5.424   
16         80       440.0              230            3.23       5.345   
17         40        78.7               66            4.08       2.200   
18         40        75.7               52            4.93       1.615   
19         40        71.1               65            4.22       1.835   
20         40       120.1               97            3.70       2.465  

## Basic Explorations

In [161]:
# how many rows and columns are present?
stores.shape
# (nrows, ncols)

no_of_rows = stores.shape[0]
no_of_cols = stores.shape[1]

In [163]:
# what are the column names?
stores.columns

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='object')

In [165]:
print(list(stores.columns))

['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost', 'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust', 'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure', 'StoreSegment']


In [166]:
# what are the datatypes of the columns
stores.dtypes
# pandas series, index = column names and values are the datatypes

StoreCode           object
StoreName           object
StoreType           object
Location            object
OperatingCost      float64
Staff_Cnt            int64
TotalSales         float64
Total_Customers      int64
AcqCostPercust     float64
BasketSize         float64
ProfitPercust      float64
OwnStore             int64
OnlinePresence       int64
Tenure               int64
StoreSegment         int64
dtype: object

In [169]:
# how to fetch only number columns
stores.dtypes.loc[(stores.dtypes != "object")]

OperatingCost      float64
Staff_Cnt            int64
TotalSales         float64
Total_Customers      int64
AcqCostPercust     float64
BasketSize         float64
ProfitPercust      float64
OwnStore             int64
OnlinePresence       int64
Tenure               int64
StoreSegment         int64
dtype: object

In [175]:
x3 = pd.Series(["Anil","Sravanti","Sakshi","Vivek","M","Sachin"], name="Emp_Names")
x3.index

RangeIndex(start=0, stop=6, step=1)

In [178]:
stores.dtypes.index

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='object')

In [183]:
# how to fetch only number columns
num_dtypes = stores.dtypes.loc[(stores.dtypes != "object")]
list(num_dtypes.index)

['OperatingCost',
 'Staff_Cnt',
 'TotalSales',
 'Total_Customers',
 'AcqCostPercust',
 'BasketSize',
 'ProfitPercust',
 'OwnStore',
 'OnlinePresence',
 'Tenure',
 'StoreSegment']

In [186]:
list(range(0,len(x3)))

[0, 1, 2, 3, 4, 5]

In [191]:
print(list(range(0,stores.shape[0])))
print(list(range(0,stores.shape[1])))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [201]:
nfull = stores.count()
nfull
# non null rows

StoreCode          32
StoreName          32
StoreType          32
Location           32
OperatingCost      32
Staff_Cnt          32
TotalSales         32
Total_Customers    32
AcqCostPercust     29
BasketSize         32
ProfitPercust      32
OwnStore           32
OnlinePresence     32
Tenure             32
StoreSegment       32
dtype: int64

In [200]:
# how many values are missing in each column:
nmiss = stores.shape[0] - stores.count()
nmiss
# total rows - number of non-missing rows

StoreCode          0
StoreName          0
StoreType          0
Location           0
OperatingCost      0
Staff_Cnt          0
TotalSales         0
Total_Customers    0
AcqCostPercust     3
BasketSize         0
ProfitPercust      0
OwnStore           0
OnlinePresence     0
Tenure             0
StoreSegment       0
dtype: int64

In [207]:
# what are the column names that contiain missing values?
list(nmiss.loc[nmiss != 0].index)

n = nmiss.loc[nmiss != 0]
names = n.index
list(names)

['AcqCostPercust']

In [208]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   StoreCode        32 non-null     object 
 1   StoreName        32 non-null     object 
 2   StoreType        32 non-null     object 
 3   Location         32 non-null     object 
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64  
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64  
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64  
 12  OnlinePresence   32 non-null     int64  
 13  Tenure           32 non-null     int64  
 14  StoreSegment     32 non-null     int64  
dtypes: float64(5), int64(6), object(4)
memory usage: 3.9+ KB


In [231]:
stores.head()

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   
3    STR104      Super Market  Super Market    Delhi           21.4   
4    STR105     Central Store  Super Market    Delhi           18.7   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   
3         60       258.0              110            3.08       3.215   
4         80       360.0              175            3.15       3.440   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  
0          16.46         0               1       4             4  
1          17.02         0               1       4             4  
2          18.61         1               1       4             1  
3          19.44         1               0       3             1  
4          17.02         0               0       3             2

In [232]:
stores.tail()

StoreCode      StoreName     StoreType Location  OperatingCost  Staff_Cnt  \
27    STR128   Super Market  Super Market  Kolkata           30.4         40   
28    STR129  Central Store  Super Market  Kolkata           15.8         80   
29    STR130   Apparel Zone       Apparel  Kolkata           19.7         60   
30    STR131  Fashion Bazar       Apparel  Kolkata           15.0         80   
31    STR132  Digital Bazar  Electronincs  Kolkata           21.4         40   

    TotalSales  Total_Customers  AcqCostPercust  BasketSize  ProfitPercust  \
27        95.1              113            3.77       1.513           16.9   
28       351.0              264            4.22       3.170           14.5   
29       145.0              175            3.62       2.770           15.5   
30       301.0              335            3.54       3.570           14.6   
31       121.0              109            4.11       2.780           18.6   

    OwnStore  OnlinePresence  Tenure  StoreSegment  
27         1               1       5             2  
28         0               1       5             4  
29         0               1       5             4  
30         0               1       5             4  
31         1               1       4             2

In [234]:
stores.head(3)

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  
0          16.46         0               1       4             4  
1          17.02         0               1       4             4  
2          18.61         1               1       4             1

In [236]:
stores.tail(3)

StoreCode      StoreName     StoreType Location  OperatingCost  Staff_Cnt  \
29    STR130   Apparel Zone       Apparel  Kolkata           19.7         60   
30    STR131  Fashion Bazar       Apparel  Kolkata           15.0         80   
31    STR132  Digital Bazar  Electronincs  Kolkata           21.4         40   

    TotalSales  Total_Customers  AcqCostPercust  BasketSize  ProfitPercust  \
29       145.0              175            3.62        2.77           15.5   
30       301.0              335            3.54        3.57           14.6   
31       121.0              109            4.11        2.78           18.6   

    OwnStore  OnlinePresence  Tenure  StoreSegment  
29         0               1       5             4  
30         0               1       5             4  
31         1               1       4             2

## Structure Manipulations

In [213]:
# 1. Subsetting columns from the data
# 1.1 Using the . operator

stores.Location

# Limitations
# a. It can only access the columns if they're named "properly"
# b. only one column can be accessed at a given time


0       Delhi
1       Delhi
2       Delhi
3       Delhi
4       Delhi
5       Delhi
6       Delhi
7       Delhi
8     Chennai
9     Chennai
10    Chennai
11    Chennai
12    Chennai
13    Chennai
14    Chennai
15    Chennai
16     Mumbai
17     Mumbai
18     Mumbai
19     Mumbai
20     Mumbai
21     Mumbai
22     Mumbai
23     Mumbai
24    Kolkata
25    Kolkata
26    Kolkata
27    Kolkata
28    Kolkata
29    Kolkata
30    Kolkata
31    Kolkata
Name: Location, dtype: object

In [215]:
# 1.2 Using [] and [[]]

#stores["Total Customers (2019)"]

stores["Location"]
stores[["StoreCode","Location","TotalSales"]]

# Limitations
# 1. we cannot work on rows

StoreCode Location  TotalSales
0     STR101    Delhi       160.0
1     STR102    Delhi       160.0
2     STR103    Delhi       108.0
3     STR104    Delhi       258.0
4     STR105    Delhi       360.0
5     STR106    Delhi       225.0
6     STR107    Delhi       360.0
7     STR108    Delhi       146.7
8     STR109  Chennai       140.8
9     STR110  Chennai       167.6
10    STR111  Chennai       167.6
11    STR112  Chennai       275.8
12    STR113  Chennai       275.8
13    STR114  Chennai       275.8
14    STR115  Chennai       472.0
15    STR116  Chennai       460.0
16    STR117   Mumbai       440.0
17    STR118   Mumbai        78.7
18    STR119   Mumbai        75.7
19    STR120   Mumbai        71.1
20    STR121   Mumbai       120.1
21    STR122   Mumbai       318.0
22    STR123   Mumbai       304.0
23    STR124   Mumbai       350.0
24    STR125  Kolkata       400.0
25    STR126  Kolkata        79.0
26    STR127  Kolkata       120.3
27    STR128  Kolkata        95.1
28    STR129  Kolkata       351.0
29    STR130  Kolkata       145.0
30    STR131  Kolkata       301.0
31    STR132  Kolkata       121.0

In [229]:
# 1.3 using .loc[,] and .iloc[,]

# [rows,cols]
# .iloc[row ix, col ix]
# .loc[row names, col names]

# stores[["StoreCode","Location","TotalSales"]]

stores.loc[:,["StoreCode","Location","TotalSales"]]


# print first 10 rows for the columns "StoreCode","Location","TotalSales"
# 0,1,2,3,4,5,6,7,8,9
# [0:10]
stores.loc[0:9,["StoreCode","Location","TotalSales"]]
stores

StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0   
1     STR102      Apparel Zone       Apparel    Delhi           21.0   
2     STR103       Super Bazar  Super Market    Delhi           22.8   
3     STR104      Super Market  Super Market    Delhi           21.4   
4     STR105     Central Store  Super Market    Delhi           18.7   
5     STR106      Apparel Zone       Apparel    Delhi           18.1   
6     STR107     Fashion Bazar       Apparel    Delhi           14.3   
7     STR108     Digital Bazar  Electronincs    Delhi           24.4   
8     STR109  Electronics Zone  Electronincs  Chennai           22.8   
9     STR110      Apparel Zone       Apparel  Chennai           19.2   
10    STR111       Super Bazar  Super Market  Chennai           17.8   
11    STR112      Super Market  Super Market  Chennai           16.4   
12    STR113     Central Store  Super Market  Chennai           17.3   
13    STR114      Apparel Zone       Apparel  Chennai           15.2   
14    STR115     Fashion Bazar       Apparel  Chennai           10.4   
15    STR116     Digital Bazar  Electronincs  Chennai           10.4   
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7   
17    STR118      Apparel Zone       Apparel   Mumbai           32.4   
18    STR119       Super Bazar  Super Market   Mumbai           30.4   
19    STR120      Super Market  Super Market   Mumbai           33.9   
20    STR121     Central Store  Super Market   Mumbai           21.5   
21    STR122      Apparel Zone       Apparel   Mumbai           15.5   
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2   
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3   
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2   
25    STR126      Apparel Zone       Apparel  Kolkata           27.3   
26    STR127       Super Bazar  Super Market  Kolkata           26.0   
27    STR128      Super Market  Super Market  Kolkata           30.4   
28    STR129     Central Store  Super Market  Kolkata           15.8   
29    STR130      Apparel Zone       Apparel  Kolkata           19.7   
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0   
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4   

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620   
1          60       160.0              110            3.90       2.875   
2          40       108.0               93            3.85       2.320   
3          60       258.0              110            3.08       3.215   
4          80       360.0              175            3.15       3.440   
5          60       225.0              105            2.76       3.460   
6          80       360.0              245            3.21       3.570   
7          40       146.7               62            3.69       3.190   
8          40       140.8               95            3.92       3.150   
9          60       167.6              123            3.92       3.440   
10         60       167.6              123            3.92       3.440   
11         80       275.8              180             NaN       4.070   
12         80       275.8              180             NaN       3.730   
13         80       275.8              180             NaN       3.780   
14         80       472.0              205            2.93       5.250   
15         80       460.0              215            3.00       5.424   
16         80       440.0              230            3.23       5.345   
17         40        78.7               66            4.08       2.200   
18         40        75.7               52            4.93       1.615   
19         40        71.1               65            4.22       1.835   
20         40       120.1               97            3.70       2.465  

In [228]:
# get first 10 rows 
stores.iloc[0:10,]

# get first 10 rows of the following column indexes 2,3,6,7,8
# 0,1,2,3..9
stores.iloc[0:10,[2,3,6,7,8]]



StoreType Location  TotalSales  Total_Customers  AcqCostPercust
0  Electronincs    Delhi       160.0              110            3.90
1       Apparel    Delhi       160.0              110            3.90
2  Super Market    Delhi       108.0               93            3.85
3  Super Market    Delhi       258.0              110            3.08
4  Super Market    Delhi       360.0              175            3.15
5       Apparel    Delhi       225.0              105            2.76
6       Apparel    Delhi       360.0              245            3.21
7  Electronincs    Delhi       146.7               62            3.69
8  Electronincs  Chennai       140.8               95            3.92
9       Apparel  Chennai       167.6              123            3.92

In [244]:
# 2. Adding columns
# derive columns from existing columns 
# 2.1 use []

# df["New Col"] = ....

stores["New1"] = 0

In [246]:
stores["New2"] = [45,23,76,54,89,43,10,30,20,33,56,21,89,10,11,63,89,22,11,40,50,20,40,60,20,90,100,220,30,40,20,33]

In [248]:
stores.head(3)

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  New1  New2  
0          16.46         0               1       4             4     0    45  
1          17.02         0               1       4             4     0    23  
2          18.61         1               1       4             1     0    76

In [251]:
# Add a column called profits
# Revenue - Expenses

# TotalSales - OperatingCost

stores["Net_Profit1"] = stores.TotalSales - stores.OperatingCost # broadcasting

stores.Net_Profit1 = stores.TotalSales - stores.OperatingCost # won't work!!!!!!!


In [252]:
stores.head()

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   
3    STR104      Super Market  Super Market    Delhi           21.4   
4    STR105     Central Store  Super Market    Delhi           18.7   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   
3         60       258.0              110            3.08       3.215   
4         80       360.0              175            3.15       3.440   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  New1  New2  \
0          16.46         0               1       4             4     0    45   
1          17.02         0               1       4             4     0    23   
2          18.61         1               1       4             1     0    76   
3          19.44         1               0       3             1     0    54   
4          17.02         0               0       3             2     0    89   

   Net_Profit1  
0        139.0  
1        139.0  
2         85.2  
3        236.6  
4        341.3

In [254]:
pd.ExcelFile?

In [273]:
# Adding a column with df = df.assign()

stores = stores.assign(New3 = "abc", 
              New4 = [45,23,76,54,89,43,10,30,20,33,56,21,89,10,11,63,89,22,11,40,50,20,40,60,20,90,100,220,30,40,20,33],
              Net_Profit2 = stores.TotalSales - stores.OperatingCost)

In [259]:
stores.head()

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   
3    STR104      Super Market  Super Market    Delhi           21.4   
4    STR105     Central Store  Super Market    Delhi           18.7   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   
3         60       258.0              110            3.08       3.215   
4         80       360.0              175            3.15       3.440   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  New1  New2  \
0          16.46         0               1       4             4     0    45   
1          17.02         0               1       4             4     0    23   
2          18.61         1               1       4             1     0    76   
3          19.44         1               0       3             1     0    54   
4          17.02         0               0       3             2     0    89   

   Net_Profit1  
0        139.0  
1        139.0  
2         85.2  
3        236.6  
4        341.3

In [271]:
# Deleting columns
# del object

del stores["New1"]


In [274]:
stores.head()

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   
3    STR104      Super Market  Super Market    Delhi           21.4   
4    STR105     Central Store  Super Market    Delhi           18.7   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   
3         60       258.0              110            3.08       3.215   
4         80       360.0              175            3.15       3.440   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  New2  \
0          16.46         0               1       4             4    45   
1          17.02         0               1       4             4    23   
2          18.61         1               1       4             1    76   
3          19.44         1               0       3             1    54   
4          17.02         0               0       3             2    89   

   Net_Profit1 New3  New4  Net_Profit2  
0        139.0  abc    45        139.0  
1        139.0  abc    23        139.0  
2         85.2  abc    76         85.2  
3        236.6  abc    54        236.6  
4        341.3  abc    89        341.3

In [277]:
# Using df = df.drop()
# Task : delete New2	New3	New4	Net_Profit2

stores = stores.drop(columns=["New2","New3","New4","Net_Profit2"])

In [278]:
stores.drop(columns=[0,1,2])  # we cannot delete by indexes

KeyError: '[0 1 2] not found in axis'

In [283]:
stores.drop(stores.columns[[1,2,3]], axis=1)
stores.columns[[1,2,3]]

Index(['StoreName', 'StoreType', 'Location'], dtype='object')

In [279]:
stores.head()

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   
3    STR104      Super Market  Super Market    Delhi           21.4   
4    STR105     Central Store  Super Market    Delhi           18.7   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   
3         60       258.0              110            3.08       3.215   
4         80       360.0              175            3.15       3.440   

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  Net_Profit1  
0          16.46         0               1       4             4        139.0  
1          17.02         0               1       4             4        139.0  
2          18.61         1               1       4             1         85.2  
3          19.44         1               0       3             1        236.6  
4          17.02         0               0       3             2        341.3

In [284]:
# Renaming columns


# From stores data, rename 
# Net_Profit1  --->  Profit
# OnlinePresence ----> Ecomm

# df = df.rename(columns = {"ExistingName1":"NewName1","ExistingName2":"NewName2","ExistingName3":"NewName3",...})
# {"ExistingName1":"NewName1","ExistingName2":"NewName2","ExistingName3":"NewName3",...}

stores = stores.rename(columns={"Net_Profit1":"Profit","OnlinePresence":"Ecomm"})

In [285]:
stores.head(3)

StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0   
1    STR102      Apparel Zone       Apparel    Delhi           21.0   
2    STR103       Super Bazar  Super Market    Delhi           22.8   

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620   
1         60       160.0              110            3.90       2.875   
2         40       108.0               93            3.85       2.320   

   ProfitPercust  OwnStore  Ecomm  Tenure  StoreSegment  Profit  
0          16.46         0      1       4             4   139.0  
1          17.02         0      1       4             4   139.0  
2          18.61         1      1       4             1    85.2

In [288]:
# Task : Profit --> 16th column
# moved towards Operating Cost and TotalSales
# Profit --> 15
# OperatingCost --> 4
# TotalSales --> 6



stores.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]
stores.iloc[:,[6,8,9,3,15,0,12,11,7,4,14,15,2,1,5,13]]


TotalSales  AcqCostPercust  BasketSize Location  Profit StoreCode  Ecomm  \
0        160.0            3.90       2.620    Delhi   139.0    STR101      1   
1        160.0            3.90       2.875    Delhi   139.0    STR102      1   
2        108.0            3.85       2.320    Delhi    85.2    STR103      1   
3        258.0            3.08       3.215    Delhi   236.6    STR104      0   
4        360.0            3.15       3.440    Delhi   341.3    STR105      0   
5        225.0            2.76       3.460    Delhi   206.9    STR106      0   
6        360.0            3.21       3.570    Delhi   345.7    STR107      0   
7        146.7            3.69       3.190    Delhi   122.3    STR108      0   
8        140.8            3.92       3.150  Chennai   118.0    STR109      0   
9        167.6            3.92       3.440  Chennai   148.4    STR110      0   
10       167.6            3.92       3.440  Chennai   149.8    STR111      0   
11       275.8             NaN       4.070  Chennai   259.4    STR112      0   
12       275.8             NaN       3.730  Chennai   258.5    STR113      0   
13       275.8             NaN       3.780  Chennai   260.6    STR114      0   
14       472.0            2.93       5.250  Chennai   461.6    STR115      0   
15       460.0            3.00       5.424  Chennai   449.6    STR116      0   
16       440.0            3.23       5.345   Mumbai   425.3    STR117      0   
17        78.7            4.08       2.200   Mumbai    46.3    STR118      1   
18        75.7            4.93       1.615   Mumbai    45.3    STR119      1   
19        71.1            4.22       1.835   Mumbai    37.2    STR120      1   
20       120.1            3.70       2.465   Mumbai    98.6    STR121      0   
21       318.0            2.76       3.520   Mumbai   302.5    STR122      0   
22       304.0            3.15       3.435   Mumbai   288.8    STR123      0   
23       350.0            3.73       3.840   Mumbai   336.7    STR124      0   
24       400.0            3.08       3.845  Kolkata   380.8    STR125      0   
25        79.0            4.08       1.935  Kolkata    51.7    STR126      1   
26       120.3            4.43       2.140  Kolkata    94.3    STR127      1   
27        95.1            3.77       1.513  Kolkata    64.7    STR128      1   
28       351.0            4.22       3.170  Kolkata   335.2    STR129      1   
29       145.0            3.62       2.770  Kolkata   125.3    STR130      1   
30       301.0            3.54       3.570  Kolkata   286.0    STR131      1   
31       121.0            4.11       2.780  Kolkata    99.6    STR132      1   

    OwnStore  Total_Customers  OperatingCost  StoreSegment  Profit  \
0          0              110           21.0             4   139.0   
1          0              110           21.0             4   139.0   
2          1               93           22.8             1    85.2   
3          1              110           21.4             1   236.6   
4          0              175           18.7             2   341.3   
5          1              105           18.1             1   206.9   
6          0              245           14.3             4   345.7   
7          1               62           24.4             2   122.3   
8          1               95           22.8             2   118.0   
9          1              123           19.2             4   148.4   
10         1              123           17.8             4   149.8   
11         0              180           16.4             3   259.4   
12         0              180           17.3             3   258.5   
13         0              180           15.2             3   260.6   
14         0              205           10.4             4   461.6   
15         0              215           10.4             4   449.6   
16         0              230           14.7             4   425.3   
17         1               66           32.4             1    46.3   
18         1               52    

In [292]:

order = list(range(0,4)) + [6,4,15,5] + list(range(7,15))
print(order)
stores = stores.iloc[:,order]


[0, 1, 2, 3, 6, 4, 15, 5, 7, 8, 9, 10, 11, 12, 13, 14]


In [293]:
stores.head()

StoreCode         StoreName     StoreType Location  TotalSales  \
0    STR101  Electronics Zone  Electronincs    Delhi       160.0   
1    STR102      Apparel Zone       Apparel    Delhi       160.0   
2    STR103       Super Bazar  Super Market    Delhi       108.0   
3    STR104      Super Market  Super Market    Delhi       258.0   
4    STR105     Central Store  Super Market    Delhi       360.0   

   OperatingCost  Profit  Staff_Cnt  Total_Customers  AcqCostPercust  \
0           21.0   139.0         60              110            3.90   
1           21.0   139.0         60              110            3.90   
2           22.8    85.2         40               93            3.85   
3           21.4   236.6         60              110            3.08   
4           18.7   341.3         80              175            3.15   

   BasketSize  ProfitPercust  OwnStore  Ecomm  Tenure  StoreSegment  
0       2.620          16.46         0      1       4             4  
1       2.875          17.02         0      1       4             4  
2       2.320          18.61         1      1       4             1  
3       3.215          19.44         1      0       3             1  
4       3.440          17.02         0      0       3             2

In [ ]:
# To change datatype

# df = df.astype()  # str, float, int, bool, "object","float64","int64"
# pd.to_numeric(,errors = "coerce")
# pd.to_datetime()

#----------------------------------------------------------
# Task : strptime --> string parsing of date and time
#    1. what are the strptime representations for
#      day
#      month
#      year
#      hours,min,sec
#----------------------------------------------------------